---
- name: start and enable nginx
  service: name=nginx state=started enabled=yes
- name: start and enable mysql-server
  service: name=mysqld state=started enabled=yes
- name: start and enable redis
  service: name=redis state=started enabled=yes
